name: Test run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  APECSS_DIR: ${{github.workspace}}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/lib -B ${{github.workspace}}/lib -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build lib
      run: cmake --build ${{github.workspace}}/lib --config ${{env.BUILD_TYPE}}
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/examples/laserinducedcavitation/build -B ${{github.workspace}}/examples/laserinducedcavitation/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build laser-induced cavitation
      run: cmake --build ${{github.workspace}}/examples/laserinducedcavitation/build --config ${{env.BUILD_TYPE}}
    - name: Run laser-induced cavitation
      run: ${{github.workspace}}/examples/laserinducedcavitation/build/lic_apecss -options run.apecss -tend 12e-6
